### ISSUE TITLE
Cloudinary SDK for php is not working in drupal

### ISSUE THREAD

**Issue by pratika2395** [cloudinary/cloudinary_php#112]
I installed cloudinary module in Myproject/sites/all/modules/.. It is showing "Please make sure the Cloudinary SDK library is installed in the libraries directory. The Cloudinary SDK for PHP library could not be found." in admin/config/media/cloudinary and also unable to edit API settings(cloud name, API key, API secret).

**Comment by idobarnoam** [comment]
Hi @pratika2395 

We currently don't have an official Drupal SDK and don't support it, so it indeed might be the case that our PHP SDK might not work nicely in Drupal.

It is in our road-map to officially support Drupal, but there's no ETA yet.

There's a contributed Drupal code which is not maintained by Cloudinary (https://www.drupal.org/project/cloudinary), but it seems to work pretty well for some of our customers. 

We do encourage community contributions to Cloudinary's client libraries and promote them if you manage to get it working.

**Comment by pratika2395** [comment]
@idobarnoam i downloaded the cloudinary, cloudinary_php-master and libraries folder from the https://www.drupal.org/project/cloudinary. should i keep all these folders in Myproject/sites/all/modules??

**Comment by idobarnoam** [comment]
Hi @pratika2395 

That project is not something that was developed or is maintained by Cloudinary, So I can't quite let you know where the files should go.

You could try contacting the [maintainers](https://www.drupal.org/u/andriy-parkhomiuk) of the project and see if they could maybe share a better solution.

**Comment by pratika2395** [comment]
@idobarnoam okay. Thanks!! I will let you know if i get a solution

**Comment by pratika2395** [comment]
Issue got fixed. I followed these changes https://www.drupal.org/project/cloudinary/issues/2605414

**Comment by idobarnoam** [comment]
Hi @pratika2395 

Thanks for the update!

Glad to hear its working.
