### ISSUE TITLE
Server returned unexpected status code - 0 - 

### ISSUE THREAD

**Issue by iandroogmans** [cloudinary/cloudinary_php#120]
Since yesterday i am receiving following error while uploading a file to cloudinary via the uploader.
"Server returned unexpected status code - 0 -"

I've tried various things but i cannot find the issue. What could status code 0 mean? 

```
public function handle($path, File $file)
    {
        $uploader = new Uploader();
        try {
            $uploadOptions = ['resource_type' => 'auto', 'public_id' => $path, 'unique_filename' => false];
            \Log::info('Trying to upload file to cloudinary with options: '.print_r($uploadOptions, true));
            \Log::info('File: ' . print_r($file, true));
            $resource = $uploader->upload($file->getRealPath(), $uploadOptions);
        } catch (\Exception $e) {
            \Log::error('Uploading file to Cloudinary not successfull', ['context' => $e->getMessage()]);
            return false;
        }
        return $resource['url'];
    }
```

**Comment by cloudinaraz** [comment]
Hi @iandroogmans 

So far, I couldn't reproduce the error using your code on my machine.

Could you please add the entire output of your log?

**Comment by iandroogmans** [comment]
Hi @cloudinaraz 
Thank you for your response. I just found the issue, when if something goes wrong in httpfoundation/UploadedFile, the error is set as an attribute of the class which i didn't see in the first place. So basically i'm trying to upload a file that is't existing.

**Comment by cloudinaraz** [comment]
@iandroogmans I see.
Thanks for the update. Glad to hear that you've managed to quickly find where the issue was coming from.

**Comment by Aamish99** [comment]
HI @iandroogmans i am also facing similar issue can you please assist me how can i fix that?

**Comment by smouki** [comment]
hey I'm getting the same error when trying to upload mp4 using WP Cloudinary plugin vie Media Library. Images are fine. Any clues? Or should we dig inside?

**Comment by idobarnoam** [comment]
Hi @smouki Could you detail how are you perfroming the upload so we could reproduce this on our end and find out the root cause?

Note that you can open a request at support@cloudinary.com to detail further as well.

**Comment by smouki** [comment]
Hi @idobarnoam thanks for the reply.. I just try upload the video file via you WP Cloudinary plugin in Media Library and this is what I get:

![image](https://user-images.githubusercontent.com/4233972/68580259-47793800-0476-11ea-8b60-6f2b77aae9fe.png)

The video file is 3MB.. are there some other restricions maybe?
![image](https://user-images.githubusercontent.com/4233972/68580363-7e4f4e00-0476-11ea-8982-a4d3bd6fff4c.png)

The images can be uploaded with no such error and everything works as expected for them.

I will open a request with the support.. thanks!

**Comment by idobarnoam** [comment]
@smouki From the looks of the screenshot you shared, it seems that the first version of the plugin is being used.
This version does not support videos so errors might indeed happen.
You could [try our beta](https://cloudinary.com/documentation/wordpress_integration) of version 2.0 of the plugin which does support videos

Let us know if that makes sense?

**Comment by smouki** [comment]
hey @idobarnoam 

oh.. I'll try it out.. is v 2.0 production ready? ;)

**Comment by shirlymanor** [comment]
It's in beta but we have a lot of customers that are happy with the new plugin :)
