### ISSUE TITLE
Class 'Cloudinary\Api\GeneralError' not found in

### ISSUE THREAD

**Issue by Mcgurk125** [cloudinary/cloudinary_php#137]
I have copied the contents of src into my root folder/Cloudinary

Within that I have another folder named Api which contains GeneralError. However, we attempting to use $api->resources()

 I receive the below:
<b>Fatal error</b>:  Class 'Cloudinary\Api\GeneralError' not found in <b>/srv/disk4/2728061/SITE-NAME-HERE</b> on line <b>1344</b><br />

**Comment by Mcgurk125** [comment]
I noticed that the comments mention that PHP 5.4 is required. Do you mean is a minumum requirement or this exact version is needed?

**Comment by cloudinaraz** [comment]
Hi @Mcgurk125,

The PHP 5.4 is a minimum requirement.

The reason you get this error is that you did not install the package through composer.
If you do have composer in your project, running `composer dump-autoload -o` from your command line should solve the issue.

In case you don't use composer and would like to fix the issue manually, you can try and add the following the top of your Api.php file (which in your case is located in the root folder):

```
namespace Cloudinary\Api {
  class Error extends \Exception {}
  class NotFound extends Error {}
  class NotAllowed extends Error {}
  class AlreadyExists extends Error {}
  class RateLimited extends Error {}
  class BadRequest extends Error {}
  class GeneralError extends Error {}
  class AuthorizationRequired extends Error {} 
  class Response extends \ArrayObject {
    function __construct($response) {        
        parent::__construct(\Cloudinary\Api::parse_json_response($response));
        $this->rate_limit_reset_at = strtotime($response->headers["X-FeatureRateLimit-Reset"]);
        $this->rate_limit_allowed = intval($response->headers["X-FeatureRateLimit-Limit"]);
        $this->rate_limit_remaining = intval($response->headers["X-FeatureRateLimit-Remaining"]);
    }    
  }  
} 
```

**Comment by Mcgurk125** [comment]
That has worked! Thank you. I am now just getting a connection refused, do you know if that is common issue on shared hosting?

**Comment by cloudinaraz** [comment]
@Mcgurk125 I can see that you also have an open ticket with us on our support system, related to the same issue. It seems like you've managed to solve the connection refused error that you've been experiencing. Is that correct?

**Comment by Mcgurk125** [comment]
Yes all good thanks

**Comment by vjnvisakh** [comment]
thank you so much

**Comment by cloudinaraz** [comment]
@vjnvisakh you're welcome. Just please note that although this solution works, it is most advised that you use the autoloader.php approach that I suggested you in the support ticket you opened.
