### ISSUE TITLE
Unit-Tests not working localy

### ISSUE THREAD

**Issue by flow-control** [cloudinary/cloudinary_php#162]
Hey there,

when i try to run the unit-tests localy via
> $ php vendor/bin/phpunit

i get a bunch of errors stating:
> 97) Cloudinary\UploaderTest::test_responsive_breakpoints_format Cloudinary\Error: Unknown API key 123456789012345`

I would really like to help, and update PHP-Unit to a more recent version, could you provide me with a Testing-API-Key?

Kind regards
Florian

**Comment by cloudinaraz** [comment]
Hey @flow-control,

You can set an environment variable CLOUDINARY_URL which can be copied directly from your dashboard when logging into your account via the web interface.
It should be of the following pattern, using your account's credentials:
cloudinary://API_KEY:API_SECRET@CLOUD_NAME 

Once set, you should be able to run all tests without any failures.

**Comment by flow-control** [comment]
Thanks for your reply. I already thought of that, but I wonder if that will have an impact on my credits. And I don't know how much running phpunit will cost me.

Do you know how much credits running the test suite will cost me?

**Comment by flow-control** [comment]
Hey @cloudinaraz,

i added my own API-Key and the tests were working (except one which was caused by a missing ZipArchive Class, my fault). But my Account was a little messed up ;-)
It used 0.04 of my credits, uploaded 26 images without removing them and a bunch of transformations (also did not cleanup this).

I close this issue for now. Would you accept a PR updating the deps to a newer level and cleaning up the  tests a bit to cleanup afterwards, or better split the tests to unit and integration tests?

Would you mind dropping PHP5 Support?

Kind regards
Florian

**Comment by cloudinaraz** [comment]
@flow-control thank you for your interest in contributing to our PHP library!
We would love to get your PR with tests cleanup (and possibly splitting them to unit/integration).

With regard to PHP5 support, as it is still a very popular version among PHP developers, I'm afraid that we currently cannot drop support for it.
