### ISSUE TITLE
"Only variables should be passed by reference" when calling generate_sprite

### ISSUE THREAD

**Issue by bperel** [cloudinary/cloudinary_php#165]
Hi,

I have just started using the Cloudinary API so maybe I am doing something stupid, but when calling `generate_sprite`, for example with :
```php
\Cloudinary\Uploader::generate_sprite('mytag');
```

I get the error : 
`Notice: Only variables should be passed by reference`

The problem gets solved if I make Cloudinary's `generate_transformation_string` function not take arguments by reference but by value, i.e. replace 
```php
generate_transformation_string(&$options = array())
```
by 
```php
generate_transformation_string($options = array())
```
in `cloudinary/cloudinary_php/src/Cloudinary.php:504`.

Is there a way to not have the notice be triggered without manually changing the API's source?

I am using PHP 7.2, but I don't think that it matters here.

**Comment by cloudinaraz** [comment]
Hi @bperel,

Thanks for bringing this to our attention.

Please note that this is not an actual error but a "Notice".
Nevertheless, we will indeed fix it soon, hopefully for the next version.

In the meanwhile, if you do desire to keep the local changes to the source, so it will work without any notices, please make sure that you return the pointer in the `generate_transformation_string()` method definition, as it is important to keep it this way in case you pass any options when calling other functions as well.
Instead, you can try and replace the following in Uploader.php lines 213-215:

```
$transformation = \Cloudinary::generate_transformation_string(
    array_merge(array("fetch_format" => \Cloudinary::option_get($options, "format")), $options)
);
```

With something similar to:

```
$transOptions = array_merge(array("fetch_format" => \Cloudinary::option_get($options, "format")), $options);
$transformation = \Cloudinary::generate_transformation_string($transOptions);
```

However, as mentioned above, we will implement the fix soon so you won't need to make the modifications yourself.

I will update you here once it will be available in the master branch.

**Comment by bperel** [comment]
Hi @cloudinaraz , yes you're right it's only a notice. On my dev environment I don't filter out any logs so it pollutes my output, that's why it bothers me :-) Thank you for the feedback, I'll make the modifications manually in `Uploader.php` and wait for an update on this ticket.

**Comment by cloudinaraz** [comment]
Hey @bperel, just wanted to let you know the fix was merged to the master branch and will be available in the next version.
In the meanwhile, if needed, you can pull the last commit from the master branch using composer.
You can use the following as reference:
https://stackoverflow.com/questions/19916183/how-do-i-get-composer-to-download-the-latest-commit-in-the-master-branch-from-gi
