### ISSUE TITLE
Development 

### ISSUE THREAD

**Issue by damcclean** [cloudinary/cloudinary_php#171]
Hey,

I see that the only way of uploading files is by specifying a URL with the media. However, how can I do this in development? When I try and upload from development, I get a DNS error, because my localhost is unreachable from Cloudinary.

Is there any way of upload the file contents instead of specifying a url? 

Thanks

**Comment by roeeba** [comment]
Hi @damcclean. There are several ways to upload content to your Cloudinary account. As shown in [our docs](https://cloudinary.com/documentation/image_upload_api_reference#upload_method) - 

> The file to upload can be:
> 
> 1. a local file path (supported in SDKs only)
> 2. the actual data (byte array buffer). For example, in some SDKs, this could be an IO input stream of the data (e.g., File.open(file, "rb")).
> 3. the Data URI (Base64 encoded), max ~60MB (62,910,000 chars)
> 4. the remote FTP, HTTP or HTTPS URL address of an existing file
> 5. a private storage bucket (S3 or Google Storage) URL of a whitelisted bucket

Can you please share what exactly have you tried and didn't work for you so we can take a closer look?

**Comment by damcclean** [comment]
Hmm, didn't realise I could pass in the actual base64 encoded version of the file. This means I now have this:

```
\Cloudinary::config([
            'cloud_name' => config('readcast.cloudinary.cloud'),
            'api_key' => config('readcast.cloudinary.key'),
            'api_secret' => config('readcast.cloudinary.secret'),
        ]);

        // Upload to Cloudinary
        \Cloudinary\Uploader::upload(base64_encode($response->getBody()), [
            'resource_type' => 'video',
            'public_id' => config('app.env') . '/' . $slug
        ]);
```

My only issue now is when I attempt to upload to Cloudinary I get a `cURL error 28: SSL connection timeout (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)` error which suggests there is some SSL/HTTPS security issue somewhere. Is this something on my end, the SDK's end or Cloudinary's end and how can I fix it?

**Comment by roeeba** [comment]
Hi @damcclean. It is likely that you're getting a timeout because your video is too big to be sent in one go. Please use the `upload_large` method instead - 
https://github.com/cloudinary/cloudinary_php/blob/f3b084d9e5fa67f3a0ecba931cd9da513ddf665b/src/Uploader.php#L110

For more information - 
https://cloudinary.com/documentation/upload_videos#chunked_video_upload

**Comment by damcclean** [comment]
Hmm, when I use the `upload_large` method I get another error. It starts with `fopen(...`. I can't get the end of the error because the base64 contents of the file is too long for it to log.

Any idea on what might be the issue?

**Comment by roeeba** [comment]
Can you please share your cloud name (so I can check your logs) and the exact code you're using that leads to the error?

If you rather keep it private, please feel free to open a support ticket at support@cloudinary.com and share the details there.

**Comment by damcclean** [comment]
My cloud name is `readcastapp`

**Comment by roeeba** [comment]
Thanks, @damcclean. However, the code you shared lacks the `upload_large` method.  

I also can't seem to find any related error in your logs. Can you please also share the exact Base64 string you're trying to upload?

**Comment by damcclean** [comment]
Oh, sorry, fetched the wrong code.

This is the base64 string that I'm attempting to upload. Maybe it's length is the issue. https://gist.github.com/damcclean/a2d7bd1f862538e75d49445cc0f1225c

**Comment by shirlymanor** [comment]
Uploading using Base64 representation is limited to file-size of 60MB. The file that you shared is 1.5MB.

**Comment by roeeba** [comment]
@damcclean, Your Base64 data URI needs to follow this scheme - https://en.wikipedia.org/wiki/Data_URI_scheme. 
You might want to refer to [this SO](https://stackoverflow.com/questions/3967515/how-to-convert-an-image-to-base64-encoding/13758760#13758760) thread for help.

**Comment by damcclean** [comment]
In the end I didn't implement Cloudinary, as I couldn't get it configured and working the way I want it. Although, thanks for your help!
