### ISSUE TITLE
Download link ends in Class not found

### ISSUE THREAD

**Issue by cherimo** [cloudinary/cloudinary_php#173]
Hey there,

I am trying to download a private file like this:

```
<?php
require '../vendor/autoload.php';
\Cloudinary\Utils::private_download_url("my_pdf2.pdf", "pdf" , array("attachment" => true));
```

But the end result is the next error:
Fatal error: Uncaught Error: Class 'Cloudinary\Utils' not found...

Am I doing something wrong here?

**Comment by cloudinaraz** [comment]
@cherimo the `private_download_url()` method is defined in the Cloudinary class and not in Cloudinary\Utils.
Removing Utils from your call should resolve this error:

```
$download_url = \Cloudinary::private_download_url("my_pdf2.pdf", "pdf" , array("attachment" => true));

echo $download_url;
```

Let me know if it works for you?

**Comment by cherimo** [comment]
@cloudinaraz 
Thx the error is gone.

The link that it produced is getting me this: 
`{"error":{"message":"Resource not found - my_pdf2.pdf"}}`

I uploaded the file with the next line (With success):
`\Cloudinary\Uploader::upload("test.pdf", array("folder" => "pdf/", "public_id" => "my_pdf2", "type" => "private"));`

I also tried to generate the link with my_pdf2 as public_id and also tried to use the folder name but I am getting the same result: Resource not found.

Did i miss something? 

Thx in advance.

**Comment by cloudinaraz** [comment]
@cherimo I see.
So you uploaded the PDF document with `image` type.
The file extension of resources with `image` type is not a part of the public_id.
Therefore, you should only pass `my_pdf2` in the public_id parameter and remove the `.pdf` part of the string:

```
$download_url = \Cloudinary::private_download_url("my_pdf2", "pdf" , array("attachment" => true));
```

Can you please try again?

**Comment by cherimo** [comment]
This works perfectly fine:
```
\Cloudinary\Uploader::upload("test.pdf", array( "public_id" => "my_pdf2", "type" => "private"));
$download_url = \Cloudinary::private_download_url("my_pdf2", "pdf" , array("attachment" => true));
```
But when I add the 'pdf' folder, I get this error: Resource not found - my_pdf3
```
\Cloudinary\Uploader::upload("test.pdf", array("folder" => "pdf/", "public_id" => "my_pdf3", "type" => "private"));
$download_url = \Cloudinary::private_download_url("my_pdf3", "pdf" , array("attachment" => true));
```

So it seems that when I upload the file inside a folder, the download doesnt work. If I move the file from the 'pdf' folder to 'home' folder the download link is working perfectly.

**Comment by cloudinaraz** [comment]
@cherimo the folder hierarchy is part of the public_id of the resource.
Therefore, when generating the private download URL using the designated method, any folder path should be concatenated as a prefix to the resource name.
In your case it will be `pdf/my_pdf3` and overall:

```
$download_url = \Cloudinary::private_download_url("pdf/my_pdf3", "pdf" , array("attachment" => true));
```

**Comment by cherimo** [comment]
@cloudinaraz thanks that did the trick :)
