### ISSUE TITLE
Call to a member function dispense() on a non-object

### ISSUE THREAD

**Issue by toby78** [cloudinary/cloudinary_php#18]
Fatal error: Call to a member function dispense() on a non-object in PhotoAlbum/lib/rb.php on line 7511

?

This happen when uploading an image on the PhotoAlbum demo app.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
