### ISSUE TITLE
Issue with special characters when uploading

### ISSUE THREAD

**Issue by jbardnz** [cloudinary/cloudinary_php#185]
I am trying to upload images and apply a text overlay transformation at the same time. Here is the code I am using:

```
  $result = Uploader::upload("https://images.unsplash.com/photo-1446292267125-fecb4ecbf1a5?w=700", array("transformation" => array(
            array( "overlay" => [
                "font_family" => 'Arial',
                "font_size"=> 40,
                "text" => 'This has, a comma',
            ],
                "color" => "#fff"
            )

        )));
```

And this is the result:
![Result](http://res.cloudinary.com/blerbhq/image/upload/v1568551723/z1bp8i01qy8rdsjadlwq.jpg)

I have tried using `urlencode()` around the text as well but that seemed to make the issue worse (the comma was then double encoded). 

Am I doing something wrong with the way I pass text to the library?

**Comment by shirlymanor** [comment]
@jbardnz You can try using urlencode() twice and the expected result: 
%252C
For example:
http://res.cloudinary.com/demo/image/upload/l_text:arial_40:Hi%252Cuser%20name/sample.png

**Comment by jbardnz** [comment]
Hi Shirly, 

Thanks for getting back to me, I have updated my code to the following:

```
 $result = Uploader::upload("https://images.unsplash.com/photo-1446292267125-fecb4ecbf1a5?w=700", array("transformation" => array(
            array( "overlay" => [
                "font_family" => 'Arial',
                "font_size"=> 40,
                "text" => 'This has' . urlencode(urlencode(',')) . ' a comma',
            ],
                "color" => "#fff"
            )

        )));
```


And this is the result:
![result](http://res.cloudinary.com/blerbhq/image/upload/v1568556262/yyajqr4kodvhwmiqmrjv.jpg)

**Comment by leptians** [comment]
Hi @jbardnz , there is an issue with the encoding for incoming transformation. We are going to fix this. In the mean time, please use [named transformation](https://cloudinary.com/documentation/chained_and_named_transformations#named_transformations) as a workaround.

Example:

**Comment by jbardnz** [comment]
Hi @leptians, thanks so much for looking into this. It would be really great to get this fixed, I will use named workarounds for now, however as I have over 100 different transformations per day I feel this may get out of hand quite quickly haha.

**Comment by leptians** [comment]
Hi @jbardnz , sure, we will update you as soon as we have it fixed.

**Comment by leptians** [comment]
Hi @jbardnz , actually, you can do the following instead:

```
$result = \Cloudinary\Uploader::upload("https://images.unsplash.com/photo-1446292267125-fecb4ecbf1a5?w=700", array("transformation" => array(
    array(
        "overlay" => 'text:Arial_40:This has' . urlencode(',') . ' a comma',
        "color" => "#fff"
    )
)));
```

**Comment by jbardnz** [comment]
@leptians thanks - that workaround is really helpful.
