### ISSUE TITLE
SSL: certificate verification failed

### ISSUE THREAD

**Issue by arndtvoges** [cloudinary/cloudinary_php#19]
I started getting this error, which shows up every time I attempt an image upload.

```
Error in sending request to server - SSL: certificate verification failed (result: 5)
```

This is 1.0.12 installed via composer. I verified that src/cacert.pem exists and reinstalled all packages via composer too.

If it helps troubleshooting - no errors if I comment out the certificate configuration and disable certificate validation in your Uploader.php file:

```php
// curl_setopt($ch, CURLOPT_CAINFO,realpath(dirname(__FILE__)).DIRECTORY_SEPARATOR."cacert.pem");
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```

**Comment by tocker** [comment]
Hi @arndtvoges,

Sorry for the long delay. If this is still an issue, please open a ticket at [Cloudinary's support site](https://support.cloudinary.com).
