### ISSUE TITLE
PHP v7.4 Issue

### ISSUE THREAD

**Issue by RWAP** [cloudinary/cloudinary_php#191]
In PHP v7.4 you get a warning on various lines in cloudinary.php, such as 
implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/class/contrib/cloudinary-cloudinary_php/src/Cloudinary.php on line 536

For example:
`$angle = implode(Cloudinary::build_array(Cloudinary::option_consume($options, "angle")), ".")`

**Comment by leptians** [comment]
Hi @RWAP, thanks for noticing this. This warning seems to be introduced in PHP v7.4.

**Comment by roeeba** [comment]
Hey, I've assigned this to our engineers to review. Note that PHP v7.4 is yet to be released.
