### ISSUE TITLE
Deleting multiple IDs doesn't work

### ISSUE THREAD

**Issue by matthiasfeist** [cloudinary/cloudinary_php#20]
The API Class generates a wrong URL when deleting multiple Public IDs.

When I run the API Documentation Example:
`$api = new \Cloudinary\Api();	
$result = $api->delete_resources(array("image1", "image2"));`
The Class generated the following URL:
`https://api.cloudinary.com/v1_1/limango/resources/image/upload?public_ids%5B%5D=image1&public_ids%5B%5D=image2`
Which is faulty according to the API and results in throwing a "General Error" Exception

**Comment by taragano** [comment]
I'm sorry for my response delay.

Just wanted to check about the generated URL not being conformed with the API documentation. Does this issue still happen for you? Can you please share an example of the a returned URL vs. what you would expect it to be?

**Comment by taragano** [comment]
@matthiasfeist - Do you still experience this issue?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
