### ISSUE TITLE
Support of guzzlehttp/guzzle ^7.0.1

### ISSUE THREAD

**Issue by wizard-85** [cloudinary/cloudinary_php#219]
## Feature request for Cloudinary-laravel
Please Add support of guzzlehttp/guzzle ^7.0.1 

## Explain your use case
guzzlehttp/guzzle ^7.0.1  is User by Laravel 8, without support - Cloudinary-laravel and cloudinary_php can't be installed on new Versions of Laravel

[https://github.com/cloudinary-labs/cloudinary-laravel/issues/11](https://github.com/cloudinary-labs/cloudinary-laravel/issues/11)

**Comment by const-cloudinary** [comment]
@wizard-85 , the new version of the SDK was released, [2.0.0-beta7](https://github.com/cloudinary/cloudinary_php/releases/tag/2.0.0-beta7). 
I believe Cloudinary-laravel should be updated soon as well. 
If not, you can open an issue in that repo.
