### ISSUE TITLE
Add Link To 2.x Documentation

### ISSUE THREAD

**Issue by alexfinnarn** [cloudinary/cloudinary_php#222]
## Describe the problem you’re trying to solve

Pairing current docs to 2.x branch and betas.

## Do you have a proposed solution?

I like the version selector on https://symfony.com/doc/current/setup.html but realize you'd have to do this for each sdk...so I don't have a good proposed solution.

Since 2.x is in beta, I want to use that, but since I will likely only use a few API functions I might use the 1.x versions that are currently documented on https://cloudinary.com/documentation/php_integration. I see you have "v1" in the page title there, but I have no idea when v2 docs go up.

**Comment by leptians** [comment]
Hi @alexfinnarn , SDK v2 for PHP documentation is available on the following page: https://cloudinary.com/documentation/php2_integration

**Comment by const-cloudinary** [comment]
Now default [Documentation](https://cloudinary.com/documentation/php_integration) is for v2 SDK.
