### ISSUE TITLE
Update shrikeh/teapot depedency to 2.*

### ISSUE THREAD

**Issue by lowki** [cloudinary/cloudinary_php#223]
## Feature request for Cloudinary PHP SDK
Update shrikeh/teapot depedency to 2.*

## Explain your use case
phpcs v3.* requires shrikeh/teapot ^2 and cannot be used

**Comment by const-cloudinary** [comment]
@lowki , thanks for reporting this!

The issue should be resolved in [Version 2.0.0-beta8](https://github.com/cloudinary/cloudinary_php/releases/tag/2.0.0-beta8)
