### ISSUE TITLE
Recover an asset by its "asset_id"

### ISSUE THREAD

**Issue by jjdiaz** [cloudinary/cloudinary_php#224]
Hello,
Suppose I have a connector for Cloudinary that stores a reference to each asset in an external database. I can use public_id as the primary identifier to store the asset reference, but if a user moves an asset to another folder / category, the public_id changes and the link is broken.

It is possible to use the "asset_id" as a unique identifier and this id does not change in cloudinary during the asset lifecycle, but the API cannot retrieve an asset by its "asset_id".

Any idea to solve this?

Best Regards,
Joaquin

**Comment by leptians** [comment]
Hi jjdiaz,

That's correct that asset_id does not change throughout the asset's lifecycle.
In order to better understand what you are trying to achieve, can you share your use-case in detail?

Regards,
Erwin Lukas

**Comment by jjdiaz** [comment]
Hi Leptians,

1. Create a new asset on Cloudinary
2. Thanks to the Cloudinary webhook, an external conector capture the upload event and creates a new record in an external database.
3. The record contains the public_id and the asset_id.
4. From de conector, a third-party software try to recover the asset using the public_id. Thin runs ok.
5. A user moves the asset to another folder, so the public_id changes.
6. Cloudinary generates a new event rename.
7. The connector update the public_id in the database.
8. The access by public_id is granted.

....

I think that way it runs ok.  Sorry.

Any way. Is there any way to retrieve an asset by the API and the asset_id?.

Regards.
Joaquín Jiménez

**Comment by leptians** [comment]
Hi Joaquín,

Thanks for the details and glad you are find a solution.
Regarding retrieving an asset via API with asset_id parameter, I can see it would slightly simplify your flow. Unfortunately it's not supported.

Regards,
Erwin Lukas
