### ISSUE TITLE
Resize on folder-red image fails

### ISSUE THREAD

**Issue by codetrash** [cloudinary/cloudinary_php#23]
got this url `http://res.cloudinary.com/cvvv/image/upload/iphone.jpg` , successfully resized . when its stored in folder 
         `http://res.cloudinary.com/cvvv/image/upload/gadget/iphone.jpg`

the API return url  without 'gadget' folder
       ` http://res.cloudinary.com/cvvv/image/upload/c_fill,h_50,w_50/iphone.jpg`
instead of this correct url 
        `http://res.cloudinary.com/cvvv/image/upload/c_fill,h_50,w_50/iphone.jpg`

i use this method  
       `cloudinary_url($img, array("width" => $w, "height" => $h, "crop" => "fill"));`

**Comment by tocker** [comment]
Hi @codetrash, I'm closing this question as it has been a while.
Please feel free to reopen (or open a new issue) if you need further assistance!
