### ISSUE TITLE
Not able to specify transformation parameters directly on upload

### ISSUE THREAD

**Issue by pharsem** [cloudinary/cloudinary_php#279]
## Bug report for Cloudinary PHP SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
According to the [documentation](https://cloudinary.com/documentation/transformations_on_upload#incoming_transformations), it should be possible to use transformation parameters directly in the `options` array for uploads. I'm testing setting it up exactly as the example, with `width`, `height` and `crop` parameters, but the transformation is not applied. This is my code:

```
$cloudinary->uploadApi()->upload($file, [
       'resource_type' => 'auto',
       'type' => $public ? 'upload' : 'authenticated',
       'width' => 2000,
       'height' => 2000,
       'crop' => 'limit'
]);
```

It does however work if i use the `transformation` parameter like this: `'transformation' => 'w_2000,h_2000,c_limit'`. 

Is the documentation wrong, or is it a bug that the parameters are not working directly?

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions aren’t working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Operating System
- [ ] Linux
- [x] Windows
- [ ] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- PHP Cloudinary SDK version - 2.2.0
- PHP Version - 7.4

**Comment by Vdeub-cloudinary** [comment]
Hi @pharsem,
When using incoming transformations, we will apply the transformation to the image and save it as the original one and you will get back a URL without transformation parameters. For example, if you use this code:

```
$cloudinary->uploadApi()->upload('https://res.cloudinary.com/vdeub/image/upload/sample.jpg', [
       'resource_type' => 'image',
       'type' =>  'upload',
       'effect' => 'grayscale'
]);
```

The URL you'll get is https://res.cloudinary.com/vdeub/image/upload/v1622799987/grayscale_test.jpg which is the same as https://res.cloudinary.com/vdeub/image/upload/e_grayscale/sample.jpg but with the grayscale applied by default.

Hope that helps.
Best,
Loic

**Comment by pharsem** [comment]
Hi @Vdeub-cloudinary, 
Yes, I know how it is supposed to be working with incoming transformations, but the issue is that the transformations aren't applied when I use the `width`, `height` and `crop` parameters directly. 

I tested two uploads of the same image now. 

First one with `width`, `height` and `crop` parameters directly in the options array. As you can see from the screenshot, the image dimensions are still 5184x3456 (original size), even though I set width and height to 2000.

Second one I instead used `'transformation' => 'w_2000,h_2000,c_limit'` in the options array, and as you can see from the screenshot this worked.

![image](https://user-images.githubusercontent.com/4425612/120783190-11554a80-c52b-11eb-9cff-9fff4d8d766e.png)

So `width`, `height` and `crop` does not seem to be working directly.

**Comment by Vdeub-cloudinary** [comment]
Hi @pharsem,
Could you please share your cloudname at least I can have a look at our log and see what's going on?
Thanks!

**Comment by pharsem** [comment]
@Vdeub-cloudinary the cloudname is `schibsted-norge-smb`

**Comment by pharsem** [comment]
@Vdeub-cloudinary I've found another issue now that might or might not be related, it seems like something is a bit off with my composer installation of the SDK. 

I've been trying to use the `$adminApi->asset()` method, but I'm just getting `Fatal error: Uncaught Error: Call to undefined method Cloudinary\Api\Admin\AdminApi::asset()`. Upon further investigation, it's clear that none of the methods from `AssetsTrait` are available in my adminApi instance. Methods from the other traits that are used in `AdminApi` are available, so there's something about the `use AssetsTrait;` that's not working, but I'm not getting any errors on it. 

As I said, I'm not sure if this is related or not, but if there's something wrong with my installation I figured that might be a reason for the transformation parameters not working as well.

I've tried to rebuild the composer autoloader, and to remove and re-install the composer package, with no luck.

**Comment by leptians** [comment]
@pharsem , for incoming transformation, you may want to pass the hash or array of hashes.
So in this example, this is what your upload request would look like:
```
$cloudinary->uploadApi()->upload($file, [
       'resource_type' => 'auto',
       'type' => $public ? 'upload' : 'authenticated',
       'transformation' => [
            'width' => 2000,
            'height' => 2000,
            'crop' => 'limit'
       ]
]);
```
Hope this helps.

**Comment by pharsem** [comment]
Thanks @leptians, that worked. I'll use that going forward.

But I'm still confused as to why it doesn't work as per the [documentation](https://cloudinary.com/documentation/transformations_on_upload#incoming_transformations). It clearly says 

> "When using the SDK for a dynamically-typed language, the transformation parameters can be specified directly, without specifying the transformation parameter, as seen for example in the examples for Ruby, PHP, Python, and Node.js above."

and the code example for PHP v2 shows this as well:

```
$cloudinary->uploadApi()->upload("sample.jpg",  ["width" => 2000, "height" => 1000, "crop" => "limit"]);
```

Is this just an issue that I'm having, or is the documentation wrong?

**Comment by leptians** [comment]
@pharsem , thanks for pointing out the documentation. I believe the document shows incorrect syntax for PHP v2.
but let me double-check internally on this.
