### ISSUE TITLE
Wrong URL while turning on 'secure' and 'cdn_subdomain

### ISSUE THREAD

**Issue by cheyanru90** [cloudinary/cloudinary_php#28]
![screen shot 2015-04-09 at 1 12 50 pm](https://cloud.githubusercontent.com/assets/272139/7060784/2a12cb78-deba-11e4-8070-dd7a9884b802.png)

While using 'secure' together with 'cdn_subdomainm', this happens. 
It produce the wrong url, without having a dot (.) in res-xcloudinary.com/xxxxxx

it suppose to give url like res-x.cloudinary.com/xxxxx

**Comment by cheyanru90** [comment]
This could be fixed by modify the code in the function 

function unsigned_download_url_prefix()

adding a dot(.) in front of "cloudinary.com", which from this
![screen shot 2015-04-09 at 1 19 20 pm](https://cloud.githubusercontent.com/assets/272139/7060836/1ee9ff86-debb-11e4-8973-5b78fb862255.png)

to this
![screen shot 2015-04-09 at 1 19 36 pm](https://cloud.githubusercontent.com/assets/272139/7060838/241eb4f6-debb-11e4-817e-e3b4c4ef37f0.png)


Official bug fix will be greatly appreciated. Thank you Cloudinary Team for making the product great. Hope the official fix will be commit soon.

**Comment by TalLevAmi** [comment]
@cheyanru90 thanks for reporting this. Solved in master.
