### ISSUE TITLE
Generating Thumbnail from a Private Video

### ISSUE THREAD

**Issue by papa28x4** [cloudinary/cloudinary_php#288]
Please how do I generate thumbnail from a private video?

**Comment by aleksandar-cloudinary** [comment]
Hi @papa28x4,
Are you using the PHP v2 SDK or the legacy PHP v1?

**Comment by papa28x4** [comment]
I am using PHP v2 SDK

**Comment by aleksandar-cloudinary** [comment]
Thanks for confirming. Could you please try the below (assuming your public_id for the video is `sample`):

```
require './vendor/autoload.php';

use Cloudinary\Cloudinary;
use Cloudinary\Configuration\Configuration;
use Cloudinary\Asset\AssetType;
use Cloudinary\Asset\DeliveryType;

$config = new Configuration([
  'cloud' => [
    'cloud_name' => '',
    'api_key' => '',
    'api_secret' => ''
  ],
  'url' => [
    'secure' => true
  ]
]);

$cld = new Cloudinary($config);

echo $cld->video('sample.jpg')->assetType(AssetType::VIDEO)->deliveryType(DeliveryType::PRIVATE_DELIVERY)->signURL(true);
```

**Comment by papa28x4** [comment]
@aleksandar-cloudinary Thanks it works

But I have two follow up questions:

1) It doesn't work when I replace the echo with a return. I get a nested object containing the configurations

How can I return the value within a function?

2) Is it possible to pick a certain frame in the video or does it pick at random

**Comment by aleksandar-cloudinary** [comment]
You're welcome.

In regards to your questions.

1. Could you try to save the value in a variable and return that? I tested it on my side and both approaches seem to work.
2. By default the system chooses the middle frame as the thumbnail, but you can control that with the start offset (`so_` in URLs) parameter. Please see the following section in our documentation with examples - https://cloudinary.com/documentation/video_manipulation_and_delivery#generating_video_thumbnails

**Comment by papa28x4** [comment]
Thank you, the resource you pointed me to answered question 2
but I still have an issue with question 1.

`{
    "asset": {
        "asset_type": "video",
        "delivery_type": "private",
        "location": "assets",
        "filename": "dhmxsuxj02hr8xjha8bo",
        "extension": "jpg"
    },
    "cloud": {
        "cloud_name": "papa28x4"
    },
    "url": {
        "secure": true
    }
}`

this is what's returned. I'm not sure why.

**Comment by aleksandar-cloudinary** [comment]
That's interesting. Could you please share your code snippet that reproduces this? Please redact/remove the API Secret from the config as that should not be shared publicly.

**Comment by papa28x4** [comment]
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Cloudinary\Cloudinary;
use Cloudinary\Configuration\Configuration;
use Cloudinary\Asset\AssetType;
use Cloudinary\Asset\DeliveryType;
use Cloudinary\Transformation\VideoEdit;

class AssetController extends Controller
{
    public function thumbnail(){

        $config = new Configuration([
            'cloud' => [
              'cloud_name' => 'papa28x4',
              'api_key' => '**************',
              'api_secret' => '**********************'
            ],
            'url' => [
              'secure' => true
            ]
          ]);

        $cld = new Cloudinary($config);
        $url = $cld->video('assets/dhmxsuxj02hr8xjha8bo.jpg')
               ->assetType(AssetType::VIDEO)
               ->deliveryType(DeliveryType::PRIVATE_DELIVERY)
               ->videoEdit(VideoEdit::trim()->startOffset(5))
               ->signURL(true);
               
        return $url;
    }
}

```

**Comment by const-cloudinary** [comment]
@papa28x4 , try casting to string, like 
`(string)$url;`

or you can call explicitly
`$url->toUrl();`

**Comment by papa28x4** [comment]
@const-cloudinary 
This works, thank you.
