### ISSUE TITLE
Deleting all images

### ISSUE THREAD

**Issue by sourabh28** [cloudinary/cloudinary_php#29]
I want to delete all the images in cloudinary. Is there any script for it.

**Comment by cheyanru90** [comment]
There is in fact a function in the API which you can used to delete all resources from your cloudinary. Just be careful while you are calling this function, delete_all_resources()

Kindly refer to the Admin API: http://cloudinary.com/documentation/admin_api#delete_all_facebook_pictures

**Comment by taragano** [comment]
For more information:
http://support.cloudinary.com/hc/en-us/articles/202520962-How-can-I-bulk-delete-all-my-account-s-resources-

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
