### ISSUE TITLE
Method update of AssetTrait does not update metadata data

### ISSUE THREAD

**Issue by jjdiaz** [cloudinary/cloudinary_php#296]
# /src/Api/Admin/AssetsTrait.php

public function update($publicId, $options = [])
{
  $assetType = ArrayUtils::get($options, AssetType::KEY, AssetType::IMAGE);
  $type      = ArrayUtils::get($options, DeliveryType::KEY, DeliveryType::UPLOAD);
  $uri       = [ApiEndPoint::ASSETS, $assetType, $type, $publicId];

  $primitive_options = ArrayUtils::whitelist(
      $options,
      [
          ModerationStatus::KEY,
          'raw_convert',
          'ocr',
          'categorization',
          'detection',
          'similarity_search',
          'auto_tagging',
          'background_removal',
          'quality_override',
          'notification_url',
          **_'metadata'_**
      ]
  );

  $array_options = [
      'tags'               => ApiUtils::serializeSimpleApiParam(ArrayUtils::get($options, 'tags')),
      'context'            => ApiUtils::serializeContext(ArrayUtils::get($options, 'context')),
      'face_coordinates'   => ApiUtils::serializeArrayOfArrays(ArrayUtils::get($options, 'face_coordinates')),
      'custom_coordinates' => ApiUtils::serializeArrayOfArrays(ArrayUtils::get($options, 'custom_coordinates')),
      'access_control'     => ApiUtils::serializeJson(ArrayUtils::get($options, 'access_control')),
  ];

A 'metadata' parameter in $primitive_options or in $array_options is needed. And also a "serializeMetadata" method to convert the "metadata" array into an conformated string.

**Comment by momoip** [comment]
Hi there,
Thanks for reaching out.  
I've created a ticket for this issue you reported.
Regards,
Mo

**Comment by jjdiaz** [comment]
Hi,
I think the ApiUtils::serializeContext method does not work fine with multiple selection fields wich value is an array. The required transformation is a bit peculiar.
Can you check this behavior?
Regards.
Joaquin
