### ISSUE TITLE
Image transformation produces broken URL if public ID ends with .jpg

### ISSUE THREAD

**Issue by pharsem** [cloudinary/cloudinary_php#311]
## Bug report for Cloudinary PHP SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
I have some files with public IDs that end with .jpg, for example `a2920c438-52e5-4ecd-7d7f-e648ab891d24.jpg`. The URL to view these files will end with `.jpg.jpg`, and that works fine. However, when creating a transformation URL with the SDK, the URL is created with only one `.jpg` at the end. 

This code:
```
$this->image('a2920c438-52e5-4ecd-7d7f-e648ab891d24.jpg')
        ->deliveryType('authenticated')
        ->resize(Resize::limitFit()->width(48)->height(48))
        ->format(Format::auto())
        ->signUrl()
        ->toUrl();
```

will produce this url: `https://res.cloudinary.com/schibsted-norge-smb/image/authenticated/s--5gYQi73N--/c_limit,h_48,w_48/f_auto/a2920c438-52e5-4ecd-7d7f-e648ab891d24.jpg?_a=AAAEuGX`, which isn't working. 

If I try to do the same transformation through the online dashboard, I get a working link (ending with `.jpg.jpg`).

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions aren’t working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
1. Upload an image with a public ID ending with .jpg
2. Try to generate a transformation link through the SDK

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [x] All

## Environment and Frameworks (fill in the version numbers)

- PHP Cloudinary SDK version - 2.3.0
- PHP Version - 7.3

**Comment by cloudinaraz** [comment]
Hey @pharsem,

In general, the suggested approach is not to use filename extensions in asset's public ids. In order to avoid such unexpected behaviors and conflicts in URL parsing, I recommend shifting to non-extension public ids.

Nevertheless, if you prefer sticking with double extension URLs or if you have too many assets using this template and you don't want to execute an extensive rename action via a script, you can indeed "trick" the SDK to generate URLs with a double extension template by simply adding another `.jpg` to the image name as follows:

```
$this->image('a2920c438-52e5-4ecd-7d7f-e648ab891d24.jpg.jpg')
        ->deliveryType('authenticated')
        ->resize(Resize::limitFit()->width(48)->height(48))
        ->format(Format::auto())
        ->signUrl()
        ->toUrl();
```

or alternatively, you can do the extension method as follows:

```
$this->image('a2920c438-52e5-4ecd-7d7f-e648ab891d24')
        ->deliveryType('authenticated')
        ->resize(Resize::limitFit()->width(48)->height(48))
        ->format(Format::auto())
        ->extension('jpg.jpg')
        ->signUrl()
        ->toUrl();
```

**Comment by pharsem** [comment]
@cloudinaraz Okay, thanks. 

I'm not using extensions in the public ids normally, but I have a bunch of migrated files where that is the case. I will implement something that adds an extra extension where necessary. Thanks for your help!

**Comment by cloudinaraz** [comment]
My pleasure @pharsem :) 

Thanks for the update. Good thing you don't normally use extensions as part of your public ids.

If you encounter any issues with it, don't hesitate to let me know.
