### ISSUE TITLE
Fatal declaration error due to monolog change 

### ISSUE THREAD

**Issue by n8d** [cloudinary/cloudinary_php#312]
## Describe the bug in a sentence or two.
Using cloudinary_php v2.3.0 from composer, doing about anything right now results in a fatal error due to a change in the latest monolog. If I pin monolog to 2.3.3 instead of the latest 2.3.4, things work fine.

## Issue Type (Can be multiple)
- [x] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [ ] Behaviour - Functions aren’t working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Error screenshots or Stack Trace (if applicable)
```PHP Fatal error:  Declaration of Cloudinary\Log\LoggerDecorator::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /[snip]/vendor/cloudinary/cloudinary_php/src/Log/LoggerDecorator.php on line 195```

## Operating System
- [x] Linux
- [ ] Windows
- [ ] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- PHP Cloudinary SDK version - 2.3.0
- PHP Version - 8.0.10
- Framework (Laravel, Symphony, etc) - custom

**Comment by const-cloudinary** [comment]
@n8d , thanks for reporting the issue!

I couldn't reproduce the issue on my side using PHP 8.0. 

What I did find is that `monolog 2.3.4` requires `psr/log: ^1.0.1 || ^2.0 || ^3.0`
While `monolog 2.3.3` requires `psr/log: ^1.0.1 || ^2.0` which is not such a great difference. 

They both should work with `psr/log` version `1.1.4`. 

I checked my `composer.lock` file, and it uses `psr/log 1.1.4`.

The issue with the newer `psr/log` versions is that they are only compatible with PHP 8 and up, while our library is compatible with the older versions of PHP.

Try setting `psr/log: ^1` and check if it works for you with the latest version of `monolog`.

**Comment by n8d** [comment]
Hi @const-cloudinary, yes adding `"psr/log": "^1"` to composer.json downgrades psr/log from 3.0.0 to 1.1.4 and that fixes the issue. I'm on PHP 8.0.10. Here is some code to reproduce:

```php
$cloudAdmin = new Cloudinary\Api\Admin\AdminApi($config->cloudinaryUrl);
$result = (array) $cloudAdmin->asset($name);
```
