### ISSUE TITLE
Use CI

### ISSUE THREAD

**Issue by tdutrion** [cloudinary/cloudinary_php#32]
Could you enable the project both on [travis-ci](https://travis-ci.org) so the test suit is automatically triggered?

Let me know if and when it can be done and I'll do a PR adding the configuration then.

**Comment by tocker** [comment]
Hi @tdutrion,

Thanks for your suggestion. The library is now tested with travis-ci.

**Comment by unicodeveloper** [comment]
Shouldn't this issue be closed now @tocker ? Just a reminder 😊

**Comment by tdutrion** [comment]
As per @tocker comment, this issue is now closed! (took some time but we get there :p )
