### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by ruudk** [cloudinary/cloudinary_php#325]
PHP 8.1 will be released in 2 weeks and I think it's good to start testing if everything works as expected.

**Comment by const-cloudinary** [comment]
Thanks @ruudk for paying our attention on this. 
Indeed, in PHP 8.1 there are a few new deprecations that cause warnings under certain scenarios.
(like: `Deprecated: strlen(): Passing null to parameter #1`)

We'll address those before PHP 8.1 gets released.

**Comment by ruudk** [comment]
@const-cloudinary Any update on this? PHP 8.1 will be released tomorrow :)

**Comment by const-cloudinary** [comment]
@ruudk , thank you for the reminder!

The latest version [2.5.1](https://github.com/cloudinary/cloudinary_php/releases/tag/2.5.1), should work fine on PHP 8.1.

**Comment by ruudk** [comment]
Great! Thank you 🙏🏻 👏

**Comment by ruudk** [comment]
Closing as https://github.com/cloudinary/cloudinary_php/pull/332 is merged
