### ISSUE TITLE
Wrong CLOUDINARY_URL

### ISSUE THREAD

**Issue by stebogit** [cloudinary/cloudinary_php#331]
## Describe the bug in a sentence or two
The provided `CLOUDINARY_URL` value on my dashboard has the following format, please note the dot between `key` and `secret`:
```cloudinary://[<key>.<secret>@]<cloud>```

![Screen Shot 2021-11-22 at 1 32 52 AM](https://user-images.githubusercontent.com/12717225/142839123-b28b8f08-79a5-462b-ab74-2615babdf650.png)

However, [`Cloudinary\Configuration\ConfigUtils::parseCloudinaryUrl`](https://github.com/cloudinary/cloudinary_php/blob/2.0.0-beta6/src/Configuration/ConfigUtils.php#L69) expects 
```cloudinary://[<key>:<secret>@]<cloud>```

Although I'm using an old version of the laravel package (`1.0.0`, which used the SDK v2.0.0-beta6), I'm using Laravel 5.6, the code is the same on the [latest version of the PHP SDK](https://github.com/cloudinary/cloudinary_php/blob/master/src/Configuration/ConfigUtils.php#L69).

Now, simply replacing the `.` with a `:` in the provided URL everything works as expected, however I wonder why the inconsistency?

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions aren’t working as expected (such as generate URL)
- [x] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Operating System
- [x] Linux
- [ ] Windows
- [x] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- PHP Cloudinary SDK version - 2.0.0-beta6
- PHP Version - 7.1
- Framework (Laravel, Symphony, etc) - Laravel 5.6 (i.e. `cloudinary-labs/cloudinary-laravel@1.0.0`

**Comment by michalkcloudinay** [comment]
Hi @stebogit, Thanks for raising this issue. We are going to implement a fix soon. I will update here once the fix is released.

**Comment by michalkcloudinay** [comment]
Hi @stebogit, A fix for this issue was released. Please let us know if it works on your end. Thanks

**Comment by stebogit** [comment]
@michalkcloudinay I see the `CLOUDINARY_URL` value has changed on my dashboard and it now follows the expected pattern. Thanks!
