### ISSUE TITLE
Why does the response I'm getting not reflect the documentation's format?

### ISSUE THREAD

**Issue by VaelVictus** [cloudinary/cloudinary_php#345]
**Version 2.61** (Laravel 8)

Expected response:
https://cloudinary.com/documentation/image_upload_api_reference#upload_response

My implementation:
```
use Cloudinary\Api\Upload\UploadApi;
$cloudinary = new UploadApi();
$cloudinary->upload($file_name, ['upload_preset' => 'my_preset']);
```

I can make a successful upload, but when I try to get the image URL back, the response isn't what I would expect from the docs. It returns a few properties, like `headers` and `rateLimitResetAt`, with a troubling *private* property of 'storage' which contains all the information I need, inaccessible to me.

```
private 'storage' (ArrayObject) => 
    array (size=21)
      'asset_id' => string 'XXXXXXXXXXXX' (length=32)
      'public_id' => string 'report-images/php506D_gv8fhj' (length=28)
[etc...]
      'url' => string 'http://res.cloudinary.com/XXXX/image/upload/v1647629975/report-images/php506D_gv8fhj.jpg' (length=97)
      'secure_url' => string 'https://res.cloudinary.com/XXXX/image/upload/v1647629975/report-images/php506D_gv8fhj.jpg' (length=98)
```

**Comment by aleksandar-cloudinary** [comment]
Hi @VaelVictus,

Thanks for your post.

It looks like you're inspecting the returned object which contains the entire response, hence why you are getting back `headers` etc. The JSON sample response from the documentation is just the response body for a direct API call (e.g. via cURL) - but when using the SDKs, they return an object wrapping the entire response.

The actual upload response you'll receive will match the documentation for successful requests and ones that are not 'async' in which case you'll get a 'Pending' response. Therefore, if you capture the response for a successful upload in a variable and you try to access the relevant returned fields like the sample response lists, like `public_id` or `secure_url`, then you should be able to do so. For example, you could try:

```
$res = $cloudinary->upload($file_name, ['upload_preset' => 'my_preset']);
echo $res["public_id"] . "\n";
```

**Comment by VaelVictus** [comment]
Thanks for the quick reply Aleksandar, I'm happy to say I got it working as you described! I wouldn't have expected PHP to work this way, but there it is.

```
$info = $cloudinary->upload($file_name, ['upload_preset' => 'cow_preset']);
echo $info['url'];
```

If you don't mind, I'm curious about _how_ it returns the `'url'` index if it's not visible when eg: `dump()`ing it in Laravel; maybe my understanding of PHP's OOP is limited.

**Comment by aleksandar-cloudinary** [comment]
You're welcome @VaelVictus.

Do you have a copy of the entire object you're dumping? I ask because the "url" and all other sample response fields should be in the returned object.

When you try to access a field like "url" or "public_id" it'll look it up under the "storage" ArrayObject where they will be stored.

If you want to access the "headers" part of the response you could get them returned by running: `$info->headers`

**Comment by VaelVictus** [comment]
Ah, I appreciate the explanation. When I dumped it, I saw `storage` but tried to access it as if it were a public index on the returned object, not knowing it's something built into PHP and I simply had to access it without the index.

**Comment by snetts** [comment]
Just to follow up on this issue, on the `searchApi()` the results returned are as follows, not what is expected based on the documentation:

`Cloudinary\Api\ApiResponse {#454 ▼
  +rateLimitResetAt: 1657566000
  +rateLimitAllowed: 500
  +rateLimitRemaining: 485
  +headers: array:15 [▶]
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
}`
