### ISSUE TITLE
There is no tag for the 1.0.7 version.

### ISSUE THREAD

**Issue by daiglej** [cloudinary/cloudinary_php#35]
I am trying to migrate an old project to using composer.

The project contains a 1.0.7 version of the library.
Would it be possible to create a 1.0.7 tag with commit : 62c4da6

A simple matter of :
git tag -a 1.0.7 62c4da6
git push origin --tags

thanks!

**Comment by tocker** [comment]
Done.

**Comment by daiglej** [comment]
Great! thanks
