### ISSUE TITLE
Deprecated: fopen(): Passing null to parameter #3 ($use_include_path) of type bool is deprecated (php 8.1)

### ISSUE THREAD

**Issue by piddubnij** [cloudinary/cloudinary_php#356]
php 8.1

https://github.com/cloudinary/cloudinary_php/blob/555770d2429cf8084104eef4678550b56159aeff/src/Utils/FileUtils.php#L141

**Comment by const-cloudinary** [comment]
@piddubnij , thank you for reporting the issue!
It should be fixed in version[ 2.7.1](https://github.com/cloudinary/cloudinary_php/releases/tag/2.7.1)
