### ISSUE TITLE
Fatal Error on PHP 7.4

### ISSUE THREAD

**Issue by Nancyeleanor** [cloudinary/cloudinary_php#360]
I installed the latest version and works fine with PHP 8, but shows fatal error on PHP 7.4

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.29. in C:\xampp\htdocs\templates\vendor\composer\platform_check.php on line 24

I checked both localhost (PHP 8 and 7.4) and my hosting server (PHP 7.4)

I want to run it on PHP 7.4, pls help

**Comment by PixelCook** [comment]
Hey there, looks like you need to update your composer file to the appropriate PHP version. You can read more about different set ups in this thread https://stackoverflow.com/questions/52510527/how-can-we-change-version-requirements-for-dependency-on-composer-lock-file

**Comment by atdcloud** [comment]
@Nancyeleanor Please check your composer file and define the PHP version that is at least the same version as your PHP.
