### ISSUE TITLE
Bad signature when public id contains commas

### ISSUE THREAD

**Issue by jjdiaz** [cloudinary/cloudinary_php#361]
When the public_id contains commas the methods uploadApi()->updateMetadata and uploadApi()->upload generates an invalid signature error. However the adminApi->update method runs ok.

**Comment by cloudinaraz** [comment]
Hey @jjdiaz, the Admin API and the Upload API authentications are performed differently. While upload API indeed consists of a signature parameter, the Admin API uses Basic Authentication so the SDK doesn't generate the signature similar to the Upload API methods.

In general, special characters in the `public_id` should be encoded when making API requests, so can you please try and encode commas will be replaced with `%2C` and let me know if that solves the issue for you?

**Comment by momoip** [comment]
Hi @jjdiaz,
The call for updateMetadata looks right, but since you get no error but not find any "public_ids".  Please open a support ticket and provide me the cloud name and make the call and I can investigate from our log and let you know.

**Comment by jjdiaz** [comment]
Hello @momoip 
I just opened ticket #190154

**Comment by aksjoshi1** [comment]
Hi @jjdiaz 
Closing this issue here. We will continue on the support ticket
