### ISSUE TITLE
Incorrect URL generated when Public ID of MediaAsset ends with dot + 1-5 characters

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_php#370]
# Bug report for Cloudinary PHP SDK

## Describe the bug in a sentence or two.
When the PublicID of a MediaAsset contains a dot followed by some characters, and an extension is set, the generated URL is incorrect when the amount of following characters is between 1 and 5.

## Issue Type (Can be multiple)
- [ ] Build - Can’t install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions aren’t working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
```php
$mediaAsset = new CloudinaryMediaAsset('myImage.1', $cloudinaryConfiguration);
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.1 => OK

//Now set the extension to 'png'
$mediaAsset = new CloudinaryMediaAsset('myImage.1', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.png => NOT OK

$mediaAsset = new CloudinaryMediaAsset('myImage.12', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.png => NOT OK

$mediaAsset = new CloudinaryMediaAsset('myImage.123', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.png => NOT OK

$mediaAsset = new CloudinaryMediaAsset('myImage.1234', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.png => NOT OK

$mediaAsset = new CloudinaryMediaAsset('myImage.1234', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.png => NOT OK

$mediaAsset = new CloudinaryMediaAsset('myImage.12345', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.png => NOT OK

$mediaAsset = new CloudinaryMediaAsset('myImage.123456', $cloudinaryConfiguration);
$mediaAsset->setExtension('png');
echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.123456.png => OK!
```

This seems to be caused by the PublicID being parsed by `FileUtils::splitPathFilenameExtension()`, up until [`FileUtils::MAX_FILE_EXTENSION_LEN`](https://github.com/cloudinary/cloudinary_php/blob/72ab38b94516bb4fafd0b9f9d44c439e3184b0cf/src/Utils/FileUtils.php#L64) characters will be considered an extension, this defaults to 5.

This "limitation" of the Public ID is not documented in https://support.cloudinary.com/hc/en-us/articles/115001317409--Legal-naming-conventions

> Public ID:
> Length: between 1 and 255 characters
> Allowed characters: any language character (including non-english) and in addition dot '.' and dash '-', as well as any HTML escaped characters (E.g. “%26” as opposed to “&”)
> While '?&#\%<>+' are utterly forbidden, other special characters will be replaced with underscores '_' and preceding/trailing occurrences will be trimmed off
> Should not begin nor end with whitespace or forward-slash (those will be omitted as well)
> You cannot use 'v' followed by numeric characters as the name of a folder.

Not sure how long this problem occurred, but this "used" to work.

A workaround is to prevent using dots in the public ID and replace them with dashes or something...

However, using dots was part of our naming convention, since it makes it easily readable for humans, so a "fix" would be preferred, if possible at all 😉 

## Error screenshots or Stack Trace (if applicable)
…

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)
- PHP Cloudinary SDK version - 2.9.2
- PHP Version - 8.1.13

**Comment by const-cloudinary** [comment]
Hello @holtkamp .

The goal of the `extension` setter is to replace/set the extension of the file, no matter what it was before.

In some cases it's hard to know whether it is a file extension or just a part of the filename (like in examples you provided).

If you want to build the right URLs, you can include the desired file extension in the constructor, like:
`$mediaAsset = new CloudinaryMediaAsset('myImage.1234.jpg', $cloudinaryConfiguration);`
`echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.1234.jpg`
And you can further manipulate it the way you want:
`$mediaAsset->setExtension('png');`
`echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/myImage.1234.png`

Or you can use transformations instead, it will deliver you file in the right format:
`$mediaAsset = new CloudinaryMediaAsset('myImage.1234', $cloudinaryConfiguration);`
`$mediaAsset->format('png');`
`echo mediaAsset->toUrl(); //https://res.cloudinary.com/accountName/image/upload/f_png/myImage.1234`

**Comment by holtkamp** [comment]
Hi @const-cloudinary, thanks for the swift response. 

We intentionally store the PublicIDs of uploaded assets without extension to make it format-agnostic and stimulate serving it in whatever format is required for a certain use case.

As you suggested: by appending the extension to the PublicIDs and "not setting the extension afterwards", the problem can be circumvented, thanks!

I would suggest to document this "behaviour" / guidelines for the PublicID? 

"When using dots '.' in the end of a public ID, note that the 1-5 characters after the dots are considered as being the extension of the Media asset"

- myPublicId.1 // Extension: "1"
- myPublicId.1 // Extension: "1"
- - myPublicId.1 // Extension: "1"
- - myPublicId.1 // Extension: "1"

**Comment by dannyv-cloudinary** [comment]
Hi @holtkamp .

Thanks for the suggestion. I'll raise it to our documentation team for consideration :)

I'm going to close off this issue, but feel free to get in touch with us if you need anything further.

Thanks,
-Danny
Cloudinary Support
