### ISSUE TITLE
${var} -> {$var} for PHP 8.2 compatibility in version 1.x

### ISSUE THREAD

**Issue by rlerdorf** [cloudinary/cloudinary_php#375]
## Feature request for Cloudinary PHP SDK

Could we get a 1.20.2 release with this simple PHP 8.2 fix, please?

## Explain your use case
The code works ok in PHP 8.2, but there are annoying deprecation warnings.

## Do you have a proposed solution?
The fix is simple:
```diff
diff --git a/src/Helpers.php b/src/Helpers.php
index b89f1f0b..232d916e 100644
--- a/src/Helpers.php
+++ b/src/Helpers.php
@@ -253,7 +253,7 @@ function fetch_breakpoints($public_id, $srcset_data = array(), $options = array(
 
         $kbytes_step = (int)ceil($bytes_step / 1024);
 
-        $width_param = "auto:breakpoints_${min_width}_${max_width}_${kbytes_step}_${max_images}:json";
+        $width_param = "auto:breakpoints_${min_width}_{$max_width}_{$kbytes_step}_{$max_images}:json";
         // We use Cloudinary::cloudinary_scaled_url function, passing special `width` parameter
         $breakpoints_url = Cloudinary::cloudinary_scaled_url($public_id, $width_param, $transformation, $options);
 
@@ -827,11 +827,11 @@ function generate_media_attr($media_options)
         $media_query_conditions = [];
 
         if (!empty($media_options['min_width'])) {
-            array_push($media_query_conditions, "(min-width: ${media_options['min_width']}px)");
+            array_push($media_query_conditions, "(min-width: {$media_options['min_width']}px)");
         }
 
         if (!empty($media_options['max_width'])) {
-            array_push($media_query_conditions, "(max-width: ${media_options['max_width']}px)");
+            array_push($media_query_conditions, "(max-width: {$media_options['max_width']}px)");
         }
 
         if (empty($media_query_conditions)) {
```

**Comment by dannyv-cloudinary** [comment]
Hey @rlerdorf. Thanks for flagging this. I have raised this with the development team to be addressed in a future release of the SDK.

Thanks,
-Danny Valentine @ Cloudinary Support

**Comment by dannyv-cloudinary** [comment]
Hi @rlerdorf.

I'm afraid as this is for the legacy PHP SDK, we are no longer offering support. Instead, we'd advise you to please upgrade to the V2 SDK if possible.

Many thanks,
-Danny

**Comment by plsoucy-tapclicks** [comment]
Hi @dannyv-cloudinary,

I totally understand that you no longer want to make updates to v1 of your SDK, but our team does not have bandwidth to upgrade that currently and your SDK is the only composer package we are using that is causing issues with PHP 8.2

Given how straightforward the fix is, is there any way to get that in?

Otherwise we'll look into forking your repo, upgrading, or replacing Cloudinary.

Note that I believe that there is a miss on the first $min_width instance in @rlerdorf's diff. Here is what we've been using when testing locally:

```diff
diff cloudinary/cloudinary_php/src/Helpers.php.old cloudinary/cloudinary_php/src/Helpers.php
256c256
<         $width_param = "auto:breakpoints_${min_width}_${max_width}_${kbytes_step}_${max_images}:json";
---
>         $width_param = "auto:breakpoints_{$min_width}_{$max_width}_{$kbytes_step}_{$max_images}:json";
830c830
<             array_push($media_query_conditions, "(min-width: ${media_options['min_width']}px)");
---
>             array_push($media_query_conditions, "(min-width: {$media_options['min_width']}px)");
834c834
<             array_push($media_query_conditions, "(max-width: ${media_options['max_width']}px)");
---
>             array_push($media_query_conditions, "(max-width: {$media_options['max_width']}px)");
```


Thanks!

**Comment by const-cloudinary** [comment]
@rlerdorf @plsoucy-tapclicks , the new version [1.20.2](https://github.com/cloudinary/cloudinary_php/releases/tag/1.20.2) is released.

**Comment by plsoucy-tapclicks** [comment]
Just tested and it works well on PHP 8.2. Thanks @const-cloudinary !
