### ISSUE TITLE
Deprecations on PHP 8.2

### ISSUE THREAD

**Issue by pesseyjulien** [cloudinary/cloudinary_php#376]
Hi,

Just to report some deprecations I have on PHP 8.2 : 

`Use of "self" in callables is deprecated`

When using : 

`Api\ApiUtils::signParameters`

or 

`uploadApi->destroy`

Best,
Julien

**Comment by dannyv-cloudinary** [comment]
Hi Julien.

Thanks for getting in touch. I've raised this with our dev team, so that this can be addressed in a future release of the SDK.

Thanks,
-Danny
