### ISSUE TITLE
Get rid of `teapot-php/status-code` dependency

### ISSUE THREAD

**Issue by OrestisZag** [cloudinary/cloudinary_php#391]
Please remove the dependency on teapot-php/status-code. It is used only for the following code which can easily be replaced.

https://github.com/cloudinary/cloudinary_php/blob/1c7d6c4b2e473dbafb02720cc92fe41a1a807a40/src/Api/BaseApiClient.php#L56-L65

Currently, teapot-php/status-code blocks upgrade to PHP 8.3

**Comment by skalahasti-cloudinary** [comment]
Hi @OrestisZag ,

Thanks for contacting us. 

I have reached out to the appropriate team to check on this.

Thanks,
Sree

**Comment by const-cloudinary** [comment]
@OrestisZag it looks like `teapot-php/status-code` released a new version that does support PHP 8.3, so it shouldn't be a problem.
https://github.com/teapot-php/status-code/releases

**Comment by ruudk** [comment]
Well... the problem will be there next year again. The question is; why are you using the dependency?

You are shipping an SDK. It should require as little dependencies as possible. Especially not ones that are not needed.

**Comment by const-cloudinary** [comment]
@ruudk , yes, you are right. This dependency is not really needed. 
Removed it here:
https://github.com/cloudinary/cloudinary_php/pull/393

Thanks for raising this!

**Comment by ruudk** [comment]
Awesome! 🥳

**Comment by ruudk** [comment]
Would be great to have it tagged when you have time 🙏🏻

**Comment by const-cloudinary** [comment]
We have code freeze caused by the upcoming holidays, will release in a week or so.

**Comment by ruudk** [comment]
Thank you!
