### ISSUE TITLE
Use named parameters instead of array in Version 3

### ISSUE THREAD

**Issue by tacman** [cloudinary/cloudinary_php#397]
If Version 3 of this SDK dropped support for all EOL dependencies, it could take advantage of things like named parameters in method calls.

Currently the library supports PHP 5, whhich has been EOL for nearly 5 years, and PHP 7, which is also EOL.  There's technical debt carrying these ancient versions.  

I LOVE named parameters.  The autocomplete within an IDE makes it so much easier to code.

**Comment by dannyv-cloudinary** [comment]
Hey @tacman.
I shall close this off as this isn't an issue, but rather, a potential enhancement to the SDK. I have made the SDK team aware.
