### ISSUE TITLE
Issue with the wordpress plugin and cloudinary SDK

### ISSUE THREAD

**Issue by atanudev2001** [cloudinary/cloudinary_php#409]
I have added the wordpress plugin for cloudinary and as well as the cloudinary SDK. I want to basically create a video of the images from my FTP. I have created a custom plugin in wordpress to implement this. Here are some screenshot of my code.

Here I am calling the directory by uncommenting the require_once I am still getting the same error.
![image](https://github.com/user-attachments/assets/09037571-b4b4-44f5-917d-66c3e259bf2c)

Here is the model.
![image](https://github.com/user-attachments/assets/fa35e991-e7df-4b8d-98e7-ebfa308da664)

![image](https://github.com/user-attachments/assets/5abd0b89-7bb2-44b1-aff6-2f4eec6567b4)

**Comment by Vdeub-cloudinary** [comment]
@atanudev2001 closing this since we have a ticket already regarding this issue
