### ISSUE TITLE
PHP 8.4 compatibility: deprecations

### ISSUE THREAD

**Issue by piddubnij** [cloudinary/cloudinary_php#414]
## Describe the bug in a sentence or two.
Implicitly marking parameter as nullable is deprecated, the explicit nullable type must be used instead:

Cloudinary\Api\Provisioning\AccountApi::__construct(): $configuration
Cloudinary\Api\Provisioning\AccountApiClient::__construct(): $configuration
Cloudinary\Api\Provisioning\AccountApiClient::init(): $configuration
Cloudinary\Log\LoggerDecorator::__construct(): $config
Cloudinary\Tag\SrcSet::breakpoints(): $breakpoints
Cloudinary\Tag\BaseImageTag::breakpoints(): $breakpoints
Cloudinary\Utils::tryParseUrl(): $allowedSchemes

Cloudinary\Transformation\AudioOverlay::timeline(): $timeline
Cloudinary\Transformation\MediaOverlay::timeline(): $timeline
Cloudinary\Transformation\VideoOverlay::timeline(): $timeline
Cloudinary\Transformation\ClippingPath::__construct(): $method
Cloudinary\Transformation\QualifierMultiValue::setValue(): $value
Cloudinary\Transformation\QualifierMultiValue::setNamedValue(): $value
Cloudinary\Transformation\BaseAction::addQualifier(): $qualifier

## Issue Type (Can be multiple)
- [x] Deprecation

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [x] All

## Environment and Frameworks (fill in the version numbers)

- PHP Cloudinary SDK version - 2.14.0
- PHP Version - 8.4.1
- Framework Symphony - 7.2.0

**Comment by wissam-khalili** [comment]
Thank you for your input.
We will review this issue.
