### ISSUE TITLE
error in sending request to server couldn't open file

### ISSUE THREAD

**Issue by ahmadtibi** [cloudinary/cloudinary_php#42]
i get a cloudinary error and after further investigation i checked the uploader.php(cloudinary's api) and it seems like a curl error?

**Comment by MaorGariv** [comment]
Can you please open a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new) and share the error you receive so we would be able to further investigate?

**Comment by ahmadtibi** [comment]
hello can you close the issue? i have solved this. i had to use  realpath($pathtofile). thank you
