### ISSUE TITLE
create_upload_preset is supposed to recieve 2 parameters, but has only one

### ISSUE THREAD

**Issue by rogervila** [cloudinary/cloudinary_php#46]
Hello,

This is the link on the documentation:
http://cloudinary.com/documentation/admin_api#create_an_upload_preset

And this is the Api method:
https://github.com/cloudinary/cloudinary_php/blob/master/src/Api.php#L202-L205

In order to make it more consistent, it should accept the `$name` parameter, like the other methods.

**Comment by MaorGariv** [comment]
Hi Roger,

Thanks for your suggestion. It makes sense:)
I'll pass it on to our SDK team to make the change.

**Comment by cloudinaraz** [comment]
Hi @rogervila, I just wanted to let you know that the documentation for the `create_upload_preset()` method in PHP was updated and now only lists one argument, which is the options array that should include `name` within it.
