### ISSUE TITLE
Error in sending request to server - Couldn't resolve host 'api.cloudinary.com'

### ISSUE THREAD

**Issue by karthickms** [cloudinary/cloudinary_php#48]
Why this error occurs in local ?

Error in sending request to server - Couldn't resolve host 'api.cloudinary.com'

Please hands to me

**Comment by taragano** [comment]
- Can you please share some code snippets of your exact request?
- It could be a DNS lookup issue. Can you please verify that you can access `api.cloudinary.com` and maybe use public DNS services like Google (e.g., 8.8.8.8 IP address)?
- Are you able to perform the same request via `CURL`?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Comment by papakay** [comment]
Please i'm experiencing the same error. I've updated the composer package to 1.10.0 and still having the same problem. 

```Error in sending request to server - Could not resolve host: api.cloudinary.com```
I tried accessing api.cloudinary.com but got 403 forbidden error.

Thanks.
