### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by esurov** [cloudinary/cloudinary_php#57]
Does cloudinary_php package officially support PHP 7.1?
I see it's not configured in travis CI config.

**Comment by nadavofi** [comment]
While we haven't yet tested it with PHP 7.1, we don't know of any compatibility issues.
We will run some tests soon. Meantime if you encounter any problems, don't hesitate to raise it here and we'll be happy to look into it.

**Comment by esurov** [comment]
I didn't encounter any problem so far, but when I tried to run tests with PHP 7.1 there were 79 skipped as risky:

PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............  63 / 190 ( 33%)
............................................................... 126 / 190 ( 66%)
....................................SSSSSSSSSSSSSSSSSSSSSSSSSSS 189 / 190 ( 99%)
S                                                               190 / 190 (100%)

Time: 153 ms, Memory: 10.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 2260, Assertions: 312, Skipped: 79.

**Comment by nadavofi** [comment]
Could you please make sure you have the CLOUDINARY_URL environment variable configured properly before running the tests? Then run it again with `--verbose` for more details on the reason for skipping.

**Comment by esurov** [comment]
I have set the CLOUDINARY_URL environment variable as well as --verbose option for phpunit. Here's the output. It's much better now, but still there are 2 tests skipped:

genote:cloudinary_php gene$ phpunit --verbose

PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.1
Configuration: /Users/gene/Work/ssp/vendor/cloudinary/cloudinary_php/phpunit.xml.dist

........................S............S.........................  63 / 190 ( 33%)
............................................................... 126 / 190 ( 66%)
.....................................Array
(
    [public_id] => juyn4x5l4v7kb6ilpf7d
    [version] => 1485436168
    [signature] => b903f30d94d765c19ae79e9529b9d0baab297c52
    [width] => 241
    [height] => 51
    [format] => png
    [resource_type] => image
    [created_at] => 2017-01-26T13:09:28Z
    [tags] => Array
        (
        )

    [bytes] => 3381
    [type] => upload
    [etag] => 7dc60722d4653261648038b579fdb89e
    [url] => http://res.cloudinary.com/venatv/image/upload/v1485436168/juyn4x5l4v7kb6ilpf7d.png
    [secure_url] => https://res.cloudinary.com/venatv/image/upload/v1485436168/juyn4x5l4v7kb6ilpf7d.png
    [original_filename] => logo
)
.......................... 189 / 190 ( 99%)
.                                                               190 / 190 (100%)

Time: 1.52 minutes, Memory: 10.00MB

There were 2 skipped tests:

1) Cloudinary\ApiTest::test19_delete_derived
Not enabled by default - remove this line to test

/Users/gene/Work/ssp/vendor/cloudinary/cloudinary_php/tests/ApiTest.php:406

2) Cloudinary\ApiTest::test32_folder_listing
For this test to work, 'Auto-create folders' should be enabled in the Upload Settings, and the account should be empty of folders. Comment out this line if you really want to test it.

/Users/gene/Work/ssp/vendor/cloudinary/cloudinary_php/tests/ApiTest.php:538

OK, but incomplete, skipped, or risky tests!
Tests: 190, Assertions: 608, Skipped: 2.

**Comment by nadavofi** [comment]
These results are legit. The two skipped tests mentioned above are known to us and are pending revision. Let us know if anything else needs attention.

**Comment by esurov** [comment]
Great! Thanks. Do you have php 7.1 among php versions in travis config?

Отправлено с iPhone

**Comment by esurov** [comment]
Looks like you don't: https://github.com/cloudinary/cloudinary_php/blob/master/.travis.yml

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'


Maybe its the case to add it?


Отправлено с iPhone

**Comment by nadavofi** [comment]
We will be adding this soon. Thanks for pointing this out.

**Comment by tocker** [comment]
Travis configuration was updated to test 7.1 in fd7b51ecdd6b009cca06c9141993462edbf6dc73.
