### ISSUE TITLE
Parse error with PHP 5.5

### ISSUE THREAD

**Issue by justintilson** [cloudinary/cloudinary_php#58]
`PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /var/jenkins/workspace/Feature-branch-API-MAIN-PHP-Testing/vendor/cloudinary/cloudinary_php/src/Cloudinary.php on line 15`

The syntax below requires PHP 5.6:

`+    const USER_AGENT = "CloudinaryPHP/" . Cloudinary::VERSION;`

In your composer.json you say that minimum version of is PHP 5.3. You will either have to revert the line above or change your composer to:

        "php": ">=5.6.0",

**Comment by nadavofi** [comment]
Thanks for pointing this out. We're working on a fix that should be released shortly.
