### ISSUE TITLE
mention of wrappers for cloudinary

### ISSUE THREAD

**Issue by jrm2k6** [cloudinary/cloudinary_php#59]
Hi,

I was wondering if you guys had any plan of mentioning wrapper of the cloudinary_php library. I created and am maintaining a small Laravel wrapper for Cloudinary that seems to be use by some people, so I was wondering if it would make sense to have some documentation mentioning those.
I am sure that I am not alone.

Sorry if this is not the right location to mention that.

Thanks!

**Comment by taragano** [comment]
Hi @jrm2k6,

While we currently don't have an official Laravel library, we did publish the following article:
https://laravel-news.com/integrating-cloudinary-to-your-backend-using-a-php-solution

It's definitely on our road-map to officially support Laravel (no ETA for this yet). Regardless, we indeed encourage community contributed libraries. Please feel free to share your repository's link here, and our dev team will be happy to take a look at it. If they give us the green light, we'll be happy to mention it.

Thanks!

**Comment by jrm2k6** [comment]
Hi,
Thanks for the response, you can take a look at the package here: https://github.com/jrm2k6/cloudder

Let me know if you have any questions.

**Comment by taragano** [comment]
Oh, it seems that we indeed do :)
Thank you for that.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
