### ISSUE TITLE
PHP 5.3 not supported anymore becuase of trait use

### ISSUE THREAD

**Issue by dragosprotung** [cloudinary/cloudinary_php#62]
Because the `Cloudinary` class now uses a trait, PHP 5.3 is not supported. Should the minimum required version be bumped ?

**Comment by taragano** [comment]
Thanks @dragosprotung,

You're right, we recently added a `trait Akamai` which is indeed [not supported on PHP 5.3](http://php.net/manual/en/language.oop5.traits.php). I've passed it on to our dev team to ask for their insights. I'll let you know of any updates.

**Comment by tocker** [comment]
`trait` was removed in ded9dc1e9b3701dfbde43877aa73d1d108f680ff.
