### ISSUE TITLE
Strange code concatention instead of method call?

### ISSUE THREAD

**Issue by Coobers** [cloudinary/cloudinary_php#66]
I'm refering to: https://github.com/cloudinary/cloudinary_php/blob/a15a8cf7bca9ecb1070edc1eea4a43c32fddd2dc/src/CloudinaryField.php#L38

In line 38:
`if ($this->verifyUpload && !$preloaded.is_valid()) {`

_(!$preloaded in concatenated with function is_valid())_

I think you meant:
`if ($this->verifyUpload && !$preloaded->is_valid()) {`

_$preloaded method valid result is negated_

I'm arguing it because such method call is used afterwards.

**Comment by richgieg** [comment]
Hi @Coobers,

Thanks for reporting this. I will check this with the team and we will follow up soon.
