### ISSUE TITLE
Attempt to fetch transformation without cloudinaryId

### ISSUE THREAD

**Issue by RWAP** [cloudinary/cloudinary_php#69]
I just found a bug in my own code.

It took me ages to realise why I was not getting a transformed image back from cloudinary using my function:
`    public static function getCloudinaryThumb($cloudinaryId, $size, $jpgToPng = true, $cropType = 'fill', $format = 'jpg')
    {
		$cloud = new CloudinaryCall();
		$cloudinaryF = new CloudinaryField($cloudinaryId);
        if ($cropType == 'faceFill') {
        	$params = array('width' => $size, 'height' => $size, 'crop' => 'fill', 'gravity' => 'face');
        } else if ($cropType == 'fill') {
			$params = array('width' => $size, 'height' => $size, 'crop' => $cropType, 'gravity' => 'auto:no_faces');
        } else {
            $params = array('width' => $size, 'height' => $size, 'crop' => $cropType);
        }
        $params['format']=$format;
		if ($jpgToPng) $params['format']='png';
        return $cloudinaryF->url($params);
    }`

This always seemed to work for me, but then I realised that the images which were giving problems did not have a cloudinaryId stored with them.

Surely it would make sense to include some sort of exception or error message return from within the Cloudinary PHP to report where a missing or invalid cloudinaryID is passed, rather than just returning a null string.

This would certainly make it easier to test the code being used to call cloudinary...

**Comment by yoav-cloud** [comment]
Hi @RWAP 
thanks for bringing this to our attention.
I will request our SDK team to have a look and we will update you once there is any progress.
Yoav
