### ISSUE TITLE
Upload Broken on PHP 5.3.3

### ISSUE THREAD

**Issue by stapleup** [cloudinary/cloudinary_php#74]
Hi, I hope this finds you well. We just signed up and we are trying to intergrate your SDK in our php 5.3.3. based application to upload images. Your documentation and composer.json file says this sdk works on php 5.3.3 but we are seeing lots of parse errors on features that are missing in php 5.3. The most common error we are seeing when trying to upload image by using 
```php
\Cloudinary\Uploader::upload($file);
```
is 
`PHP Parse error:  syntax error, unexpected '[' in '/cloudinary/cloudinary_php/src/Cloudinary.php on line 281` 

Any help in this matter would be greatly appreciated.

Thanks

**Comment by MaorGariv** [comment]
Hi @stapleup,

Sorry but PHP 5.3 is not supported by our SDK. We'll update the documentation and the Readme file of this SDK to reflect the supported versions.

We support PHP 5.4 onward.

**Comment by ljacobs-sml** [comment]
I was moving forward with the integration of Cloudinary under the assumption it was available for PHP 5.3, as your readme indicates... Wish I would have seen this first, before I started getting 500 errors when I tried to include Cloudinary.php into my script.

You should really keep your documentation up to date... Now I have to go back to my client and explain that the solution proposed will no longer be viable and that they wasted money signing up for it.

The whole point of us using Cloudinary was to avoid a PHP upgrade, thus opening a can of worms in their ancient/vast framework, which would have been required to use ImageMagick + PNGQuant.

> Setup
>
> ...
>
> Or download cloudinary_php from here
> 
> **Note: cloudinary_php require PHP 5.3**

**Comment by marissa-masangcay** [comment]
Hi @ljacobs-sml, 

We deeply apologize for this inconvenience that you've experienced. It seems we updated this in our documentation (https://cloudinary.com/documentation/php_integration#php_library_features), but have yet to do so in our README. We are working on updating it now. Once again we're truly sorry for this.
