### ISSUE TITLE
Cloudinary class is in global namespace

### ISSUE THREAD

**Issue by benswinburne** [cloudinary/cloudinary_php#75]
Can this be moved into the `Cloudinary` namespace in a future version?

**Comment by tocker** [comment]
Thanks for the suggestion!

Obviously can't change now as it will break existing code, but we'll consider it for the next major release.

**Comment by holtkamp** [comment]
Any plans for a `2.0` version? After working with quite some API's, the Cloudinary one is... well... it works 🤓 

- require at least PHP 7.1 to allow return types and nullables
- PSR4 would be good to have
- allow to inject a PSR3 logger
- less procedural programming? (just a preference...)

This API is organized quite well: https://github.com/jamesryanbell/cloudflare and might serve as inspiration. 

Note this is not meant in a bad way, just feedback and having best intentions for Cloudinary for the future (which involves a great API). 😄

**Comment by taragano** [comment]
Thanks a lot for your feedback @holtkamp. We'll pass this on to our team.

**Comment by codeaid** [comment]
I actually came to open a similar "issue" asking if there are any plans to update this library to a more modern version?

No offence but the code quality in current one is rather shocking. As @holtkamp said "it works", however there are global classes, statics and snake case methods everywhere, not to mention the lack of PHP 7.1 return and parameter types. It's 2017 after all... I can't really use the main `Cloudinary` class as a service, will have to wrap it in my own class to avoid having to use statics.

I remember using Cloudinary 2-3 years ago and having come back to it now it seems like not much has changed in the meantime.

**Comment by strausr** [comment]
@codeaid Thank you for the feedback. We'll pass it along to the team for future consideration.

**Comment by certainlysylvia** [comment]
I'll add to calls for this.

I've been working on a large project for a few years and we'd love to use this but can't until it resolves the Namespacing issue at the very least.

FYI: Our work is in php7.2 and Phalcon with everything namespaced. 2017 people! :)

**Comment by cloudinaraz** [comment]
Hey everyone, I wanted to let you know that the new version is just around the corner and the beta version is already available [here](https://github.com/cloudinary/cloudinary_php/tree/2.0.0-beta).
