### ISSUE TITLE
Missing resources_by_context method

### ISSUE THREAD

**Issue by therecluse26** [cloudinary/cloudinary_php#76]
Hi, in going through your API documentation, I noticed that resources_by_context() is missing from this PHP implementation, and I'm trying to use it for a site I'm building currently. Is there any way you could get this added soon? I figured that other people would find this helpful too. Thanks!

**Comment by idobarnoam** [comment]
Hi,
Thanks for letting us know.
We have an open task with our SDK team to perform this.

I would be happy to let you know once this is implemented.

**Comment by therecluse26** [comment]
That would be awesome, thank you!

**Comment by therecluse26** [comment]
@idobarnoam any updates on this? Thanks

**Comment by idobarnoam** [comment]
Hi @therecluse26,

There is a PR which is being reviewed. Once it is approved and checked, we would push it to production.

I would keep you posted when that happens.

**Comment by jadell** [comment]
Any update on the PR? Maybe a link to it (couldn't find it in the repo PRs)? I'd also like this functionality.

**Comment by roeeba** [comment]
Hi @jadell. I apologize, but there was a confusion here. There's is currently no open PR for this issue. Our dev team is working on it, no ETA at the moment. We will update as soon as this is resolved.

**Comment by const-cloudinary** [comment]
Fixed in https://github.com/cloudinary/cloudinary_php/releases/tag/1.9.0
