### ISSUE TITLE
Dynamic SEO suffix is now available with non-private CDNs

### ISSUE THREAD

**Issue by norvinyecla** [cloudinary/cloudinary_php#79]
Currently when using a url_suffix parameter in the cloudinary_url() function, cloudinary_php throws an exception identified as "URL Suffix only supported in private CDN". 

However, according to the official Cloudinary docs, url suffixes are now usable for all plans and doesn't require private CDNs anymore. [Source](http://cloudinary.com/blog/how_to_dynamically_create_seo_friendly_urls_for_your_site_s_images)

Hopefully this updated feature will be supported in future versions of this API.

**Comment by roeeba** [comment]
Hi @norvinyecla, thank you for reporting this. We're aware of this issue and will fix this as soon as we can. 
Updates to follow.

**Comment by norvinyecla** [comment]
Thanks for the update.

**Comment by djmj** [comment]
Any updates on this feature?

**Comment by roeeba** [comment]
@norvinyecla This was fixed on version 1.9.0.
