### ISSUE TITLE
How to upload file from stream

### ISSUE THREAD

**Issue by emman-ok** [cloudinary/cloudinary_php#80]
Please I  would like to know how to upload file from php input stream.
example
$data=file_get_contents("php://input");

**Comment by taragano** [comment]
When using our PHP SDK, the `upload` method supports on of the following

+ A path to a local file
+ A remote URL
+ Or a [Base64 URI](https://support.cloudinary.com/hc/en-us/articles/203125741-Can-I-upload-using-DATA-URI-BASE64-).

For more information
http://cloudinary.com/documentation/php_image_upload#server_side_upload

You can also upload the file directly using a POST request, as described [here](http://cloudinary.com/documentation/image_upload_api_reference#upload) (see examples under 'Endpoint').

Alternatively, if it's a user-generated content, you can perform a client-side upload, i.e., upload from the browser directly to Cloudinary (bypassing your server). For more information:
http://cloudinary.com/documentation/php_image_upload#direct_uploading_from_the_browser

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
