### ISSUE TITLE
Encode URL

### ISSUE THREAD

**Issue by crichardson9** [cloudinary/cloudinary_php#87]
The method **cl_image_tag** doesn't appear to return a fully encoded URL.

Take the following filename as an example:

```
Folder's/logo.jpg
```

In order to avoid any HTML errors I would have expected the following:

```
Folder%27s%2Flogo.jpg
```

However, the following is returned and as such breaks the img element:

```
Folder's/logo.jpg
```

**Comment by d-mendoza** [comment]
Hi @crichardson9, thank you for reporting this. Updates to follow.

**Comment by ChristianGerdes** [comment]
Any updates yet?

**Comment by roeeba** [comment]
Hi @ChristianGerdes. I apologize for the delayed reply. A fix to the issue should be deployed by the end of this month. Update to follow.
